services:
  backend:
    build:
      context: .
      target: backend
    container_name: backend
    depends_on:
      - mongodb
    env_file: "./back-end/.docker.env"
    ports:
      - "3000:3000"

  frontend:
    build:
      context: .
      target: frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3001:3001"
    env_file: "./front-end/.docker.env"


  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: db
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
